### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1097]
The code of Model Builder is in machinelearning-tools, which is a private repo. We plan to make model builder an open source tool for visibility and transparency. 

There are a few blocking items that prevent model builder from moving to public repo:

- [ ] internal nuget packages, such as `Microsoft.Developer.IdentityService.Client`
- [ ] ci and pr build are also internal only. dceng/public will be a good place to move them to. 
- [ ] lacking documents, such as CONTRIBUTION.md. Must update README.md.

There are also a few nice-to-have item that's missing before open source
- [ ] building status badge
- [ ] code coverage badge
- [ ] nightly build channel

**Comment by JakeRadMSFT** [comment]
https://github.com/dotnet/machinelearning-modelbuilder/issues/724

**Comment by luisquintanilla** [comment]
AutoML API enables users to customize and even build their own Model Builder / CLI-like experiences. Therefore at this time there are no plans to open-source Model Builder & the ML.NET CLI.
