### ISSUE TITLE
July Accessibility Pass

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1627]
Epic tracking the Accessibility testing pass to ensure we meet the SLA 60 day deadline. 

Due for SLA on **September 6th**

### Partner teams: 

- [x] Problem is with VSDialog component. #1570 
- [x] Strange behavior #1643 
- [x] Strange behavior #1594 
- [x] Rohan's feedback needed here:  #1579 

### Keyboard navigation problems: 
- [x] Same fix as 1578: #1598 
- [x] Same fix as 1598: #1578 
- [x] #1573 
- [x] #1576 

### Announcment/Screen reader problem: 

- [x]  #1597 
- [x]  #1595 
- [x]  #1599 
- [x]  While not completely fixed, this is resolved as accessibility issue. Will close when we determine if we want to make the full fix. #1577 
- [x]  #1629
- [x]  #1634
- [x]  #1631

### Other
- [x]  #1596 
- [x]  #1572 
- [x] #1660

**Comment by beccamc** [comment]
Everything fixed before August 18th can be validated on rel/candidate build 16.7.2.2141903. 

Instructions for private gallery...

The private gallery is used to make it easy for beta testers to try out the latest pre-release build. Follow these steps to add our private gallery to Visual Studio.
Tools -> Options -> Environment -> Extensions -> Add Additional Gallery ->

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/5f358e38-6a3d-4a42-bb6b-b8c904619a60)

Name: Model Builder
URL: https://privategallery.blob.core.windows.net/gallery/refs/heads/rel/candidate/atom.xml

If you go to Extensions -> Manage Extensions you should see this: 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/3f3bc7a9-2457-4933-aab9-ec26a59dcb14)

If you open the Updates Section ... you should see a pending update.  

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/d27629ce-2075-4d9f-b489-910c53d62c10)

**Comment by beccamc** [comment]
For 1577, while not completely fixed, this is resolved as accessibility issue. Will close when we determine if we want to make the full fix.

**Comment by beccamc** [comment]
All issues fixed and closed. Closing this tracking item.
