### ISSUE TITLE
Improve AutoML

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#1640]
- [ ] AutoMLMonitor in Model Builder during training step
o	Can have fancy trial monitors in model builder as well
- [x] F# support in AutoML [AutoML] Can't create AutoML pipeline in F#  https://github.com/dotnet/machinelearning/issues/6207
- [ ] Don't autogenerate project in the CLI. Make it optional. Instead, do what Model Builder does today. Add any mbconfig and code-behind to an existing project

**Comment by JakeRadMSFT** [comment]
Maybe resolve with:

- https://github.com/dotnet/machinelearning-modelbuilder/issues/1591

**Comment by luisquintanilla** [comment]
Work items are tracked elsewhere. Closing this issue for now.
