### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2144]
- [ ] https://github.com/dotnet/machinelearning-modelbuilder/issues/60
- [ ] Auto Featurizer
- [ ] SQL Code Gen
- [ ] SQL Notebook https://github.com/dotnet/machinelearning-modelbuilder/issues/1935 
- [ ] https://github.com/dotnet/machinelearning-modelbuilder/issues/1431

-----------
- [ ] https://github.com/dotnet/machinelearning/issues/6128 & https://github.com/dotnet/machinelearning/issues/6133
- [ ] DataFrame supports IDataView types (especially VBuffer) so ToDataFrame() doesn’t break.https://github.com/dotnet/machinelearning/issues/6144
- [ ] https://github.com/dotnet/machinelearning-modelbuilder/issues/1756
