### ISSUE TITLE
[Epic] Cross Project Notebook 

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2145]
- [ ] Other Kernel Support
o	F# - Native F# support in VS Notebook Editor extension 
o	Powershell
o	SQL
- [x] https://github.com/dotnet/machinelearning-modelbuilder/issues/2142
- [ ] Update all graphs to use Plotly.NET
- [x] For large code cells horizontal scroll bar not visible to see top elements (https://github.com/microsoft/VS-Notebook/issues/262)
- [ ] Add diagnostic info
- [ ] Mouse Scrolling over Daytona Controls not working https://github.com/microsoft/VS-Notebook/issues/89
----- 
- [ ] Multi-Notebook Navigation
o	Links in GitHub always trying to get me to open VS … I want to stay in GitHub when I’m in GitHub and stay in VS when I’m in VS https://github.com/dotnet/csharp-notebooks/issues/41
o	Opening Notebook doesn’t include data … so I usually clone repo but links then re-download the notebook to temp. https://github.com/dotnet/csharp-notebooks/issues/42
- [ ] Debugging experience is a bit painful in Notebooks … like stepping into .NET Interactive extension’s code
