### ISSUE TITLE
Azure Integration

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#2146]
Azure Integration/MLOps
- [ ] Notebook using the SDK
---
- [ ] Model Builder using SDK 
- [ ] Model Builder DataSet work https://github.com/dotnet/machinelearning-modelbuilder/issues/1865
- [ ] Add Azure as an environment option for all scenarios. XL
- [ ] Create Docker ML.NET Azure custom curated environment file S

**Comment by JakeRadMSFT** [comment]
https://github.com/dotnet/machinelearning-modelbuilder/issues/1520
