### ISSUE TITLE
Advanced Training Options - Optimization Metrics / Exclude algorithms

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2191]
In the Model Buidler training tab, provide a dialog for "Advanced Training Options", similar to the existing "Advaced Data Options" in the data tab. In this dialog, a user should be able to:

- Select which metric they want to optimize for related to the scenario they've chosen (i.e. Value Prediction = R-Squared, Data classification = Micro-accuracy)
- Choose which algorithms to exclude from training

**Comment by luisquintanilla** [comment]
@zewditu - UI
@LittleLittleCloud - Backend

**Comment by luisquintanilla** [comment]
This issue is blocking #60 @luisquintanilla to provide design by EOW.

**Comment by luisquintanilla** [comment]
## To-Do's

@luisquintanilla 

- [ ] Provide copy for each of the scenarios in the Trainers Tab.

@LittleLittleCloud 

- [ ] Provide list of trainers used for Data Classification and Value Prediction scenarios.
- [ ] Confirm image classification uses the same metrics as classification. 
- [ ] Confirm forecasting metrics used are the same as regression (value prediction). Does forecasting use R-Squared as one of the optimization metrics?

@zewditu 

- [ ] Confirm whether Azure ML supported scenarios (image classification / object detection) allow for setting the evaluation metric. 

## Proposed Design

![image](https://user-images.githubusercontent.com/46974588/191414656-932d1a08-2d9f-4835-b0de-37b088f9ba31.png)

![image](https://user-images.githubusercontent.com/46974588/191414551-4ea0db72-1163-4bc4-9329-d2e2a20e5bd5.png)

## Copy

### Optimizing Metric Tab

> Note: For each of the scenarios, set the default to the metric being used today.

Heading: Choose the metric that will be used to find the best-performing model.
Subheading: [When should I use each metric?](https://learn.microsoft.com/dotnet/machine-learning/resources/metrics)

#### Data classification

##### Binary Classification

> Note: This is determined based on whether the label column is boolean.

- Accuracy - The closer to 1.00, the better.
  - The ratio of number of correct predictions to the total number of input samples.
- Area under the curve (AUC) - The closer to 1.00, the better. 
  - The area under the curve created by sweeping the true positive rate vs. the false positive rate. 
- Area under the curve of a Precision-Recall curve (AUCPR) - The closer to 1.00, the better.
  - Useful measure of success of prediction when the classes are imbalanced (highly skewed datasets).
- F1-score - The closer to 1.00, the better.
  - It's the harmonic mean of the precision and recall.

##### Multiclass Classification

- Micro-Accuracy - The closer to 1.00, the better.
  - Aggregates the contributions of all classes to compute the average metric. Doesn't take into account class membership.
- Macro-Accuracy - The closer to 1.00, the better.
  - The average accuracy at the class level. Takes into account class membership.
- Logarithmic loss (Log-Loss) - The closer to 0.00, the better.
  - The performance of a classification model where the prediction input is a probability value between 0.00 and 1.00.
- Logarithmic loss reduction (Log-Loss Reduction) - Ranges from -inf and 1.00, where 1.00 is perfect predictions and 0.00 indicates mean predictions.
  - The advantage of the classifier over a random prediction.

#### Value prediction

- R-Squared - The closer to 1.00, the better quality.
  - How close the actual data values are to the predicted values.
- Mean Absolute Error (MAE) - The closer to 0.00, the better quality.
  - The average of all the model errors, where model error is the absolute distance between the predicted value and the actual value.
- Mean Squared Error (MSE) - It is always non-negative, and values closer to 0.00 are better.
  - The squared average of all model errors, where model error is the absolute distance between the predicted value and the actual value. 
- Root Mean Squared Error (RMSE) - It is always non-negative, and values closer to 0.00 are better.
  - The squared root of the mean squared error of all model errors, where model error is the absolute distance between the predicted value and the actual value. 

#### Image classification

Same as data classification. Disable for cloud scenario. Azure ML environment does not allow to specify metric.

#### Recommendation

Same as value prediction.

#### Object Detection

Disabled for now. Azure ML scenario does not allow to specify metric.

#### Forecasting

Same as value prediction.

### Trainers Tab

Heading: Choose the trainers to explore during training.
Subheading: [Which trainer should I use?](https://learn.microsoft.com/dotnet/machine-learning/how-to-choose-an-ml-net-algorithm)

#### Data classification

#### Value prediction

#### Image classification

Disabled for now: `ImageClassification` and Azure ML are the only options depending on the environment (Local vs. Cloud).

#### Recommendation

Disabled for now. `MatrixFactorization` is the only option

#### Object Detection

Disabled for now. Azure ML is the only option.

#### Forecasting

Disabled for now. `ForecastBySsa` is the only option.

**Comment by zewditu** [comment]
For  Image classification : `Accuracy, Average Precision Score Weight, AUC weighted , normalized macro recall`
OD: we only have one` MeanAveragePrecision`.

**Comment by zewditu** [comment]
One thing want to confirm one thing ,  when we say " Image classification metrices are the same as data classification",  are we talking about the `muti-classification`  one?

**Comment by luisquintanilla** [comment]
> One thing want to confirm one thing , when we say " Image classification metrices are the same as data classification", are we talking about the `muti-classification` one?

Good question. I think it's multiclass. @LittleLittleCloud do you know?

**Comment by luisquintanilla** [comment]
@LittleLittleCloud can you please take a look at the descriptions I provided for the trainers to make sure I accurately captured the main points.
