### ISSUE TITLE
Bug Bash Bugs

### ISSUE THREAD

**Issue by kawilkin** [dotnet/machinelearning-modelbuilder#311]
**Below are the bugs I wrote down from today's bug bash***

**P0 November Release**
- [x] Add label name for “results” on price prediction try our model https://github.com/dotnet/machinelearning-modelbuilder/issues/318
- [ ] Add back "latest algorithm" https://github.com/dotnet/machinelearning-modelbuilder/issues/316
- [x] For images, don't let user specify time but give them an estimate. https://github.com/dotnet/machinelearning-modelbuilder/issues/317
- [x] Add string to explain how we shrink and crop an image for image classification. https://github.com/dotnet/machinelearning-modelbuilder/issues/309

**P1 November Release**
- [ ] In Evaluate Details, Features default should have Show more (not Show less), and there should not be periods after the last Feature name or +X more
- [x] In Scenario screen, remove dash between "image classification" in description
- [x] Remove “separator” bars from each page https://github.com/dotnet/machinelearning-modelbuilder/issues/315
- [x] Make sure the dividers are using commondocument.divider token for color https://github.com/dotnet/machinelearning-modelbuilder/issues/315
- [ ] Make sure the % add up to zero
- [ ] Change the threshold so if something is “0%” it doesn’t show up as “<1%”
- [x] Align vertical dividers on the Evaluate page
- [ ] Right align percentages on Evaluate screen
<img width="184" alt="Screen Shot 2019-11-05 at 3 55 50 PM" src="https://user-images.githubusercontent.com/47866467/68257197-3e581900-ffe7-11e9-9094-ee92d595b5fb.png">

**Comment by briacht** [comment]
For "Add string to explain how we shrink and crop an image for image classification." -- what/where is this text?

**Comment by JakeRadMSFT** [comment]
Opened separate issues to track.
