### ISSUE TITLE
Azure AutoML Requests [Tracking]

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#482]
### Support Model Builder
- [ ] Communicate Errors in a user actionable way 
  - [ ] Propagate errors through client library from experiment and child experiment 
  - [ ] Preparing compute will last forever if quota exceeded
    - https://github.com/dotnet/machinelearning-modelbuilder/issues/546
- [x] All Image Models should export to ONNX for consumption by .NET Apps
- [ ] All Text Models should export to ONNX for consumption by .NET Apps

#### Client Library/SDK
- [x] Create and Support Client Library/SDK 
- [x] Support All Existing Text/Numerical/Tabular Data Scenarios
- [x] Support All Existing Image Scenarios
- [x] Support Azure ML Datasets

#### Competitive
- [ ] Better Models than Local Training
  -  [ ] Try multiple architectures
  -  [ ] Sweep more parameters

#### Scale
- [x] Faster than Local
- [x] Faster than Local w/ GPU
- [ ] Multi-GPU Support (NC12, NC24, etc ...)
- [x] Cluster/Multi-Machine Support

#### Easy to sell
- [ ] Document AutoML Costs
- [x] Reduce overhead (Time spent on HD, Image Creation, etc ...)

**Comment by JakeRadMSFT** [comment]
Local vs Azure
ASL Dataset: https://www.kaggle.com/kuzivakwashe/significant-asl-sign-language-alphabet-dataset
nc6V3 Total Time: 1h 28m 3s
nc6 Total Time: 2h 34m 59s
Local w/ GPU: 0h 38m 57s

**Comment by JakeRadMSFT** [comment]
Azure Cost Analysis:

For Image Classification and Object Detection we need Enterprise Workspaces ... for now there is no extra cost:
Source: https://azure.microsoft.com/en-us/pricing/details/machine-learning/

Charged only for Compute Hours
Source: https://azure.microsoft.com/en-us/pricing/details/virtual-machine-scale-sets/linux/

No charge for Hyper Drive/Workspace Setup

It looks like it'll be on the order of
$3 for 24 hours of training time on an NC6 Low Priority 
$15 for 24 hours of training time on an NC6 V3 Low Priority

Dedicated is about 5x the cost of Low Priority
