### ISSUE TITLE
Improve Data Parsing

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#557]
- [x] Auto-Detect Separator
- [x] Auto-Detect Header
- [x] Auto-Detect Decimal Separator ( 3.00 vs 3,00)

**Comment by beccamc** [comment]
Failure - no header 
1	2	3	4	Forge
3,6216	8,6661	-2,8073	-0,44699	0
4,5459	8,1674	-2,4586	-1,4621	0

**Comment by beccamc** [comment]
Think the yelp dataset has a header[https://app.zenhub.com/files/186917455/748b61af-c0f2-4359-a04e-adb44302e8fe/download](https://app.zenhub.com/files/186917455/748b61af-c0f2-4359-a04e-adb44302e8fe/download)

**Comment by beccamc** [comment]
Yes, we have more work to do in this space. This epic was tracking V1 PROSE integration and improvements (header, commas in data, etc.) These have been fixed. Closing this issue. Use #810, #811 and #656 to track further improvements.
