### ISSUE TITLE
Simplify Code Gen

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#558]
- [x] Remove all the load from file logic and just hard code first row from data.
- [x] Optimize for people calling into Predict multiple times
- [ ] create helper nuget to host CodeGen helper function and custom mapping
