### ISSUE TITLE
Azure Compute Improvements

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#664]
- [ ] Add support for V3 Computes (Likely requires Low Priority Support below)
- [x] Add support for Low Priority Compute Creation
- [x] NC6 should work
- [ ] Right now there is no benefit to using NC12/NC24 over NC6 ... this is coming in a couple months.
- [ ] Expose availability/quota to user.

**Comment by JakeRadMSFT** [comment]
NC6 works.
Low Pri works

**Comment by JakeRadMSFT** [comment]
V2 and V3 Fail with:
Provisioning error: Long running operation failed with status 'Failed'. Additional Info:'The specified vmSize STANDARD_NC6S_V3 belongs to a specialty Sku. It requires your subscription to be whitelisted. Please contact support to whitelist your subscription for this vmSize'

**Comment by JakeRadMSFT** [comment]
Submitted a request to increase quota using the support tool in the portal:

https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview

**Comment by JakeRadMSFT** [comment]
Spot Pricing is essentially what we leverage with Low Priority:

![image.png](https://images.zenhubusercontent.com/5cde1c65e3106e39e8ae08f2/797cd9b2-bb9a-4e35-bbb7-8d44805374ce)

https://azure.microsoft.com/en-us/pricing/details/virtual-machine-scale-sets/linux/#ncv3-series

**Comment by JakeRadMSFT** [comment]
https://azure.microsoft.com/en-us/pricing/details/machine-learning/

 

The Enterprise edition is currently in preview and there will be no ML surcharge during this time.

**Comment by JakeRadMSFT** [comment]
It looks like it's on the order of:

$5 for 24 hours of training time on an NC6 Low Priority 
$15 for 24 hours of training time on an NC6 V3 Low Priority (V3 are 4-6x faster)

Dedicated is about 5x the cost of Low Priority.

**Comment by beccamc** [comment]
@JakeRadMSFT It looks like there is a usage api exposed!! https://docs.microsoft.com/en-us/rest/api/compute/usage/list

The new UI in the cloud looks like this 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/8dc4ae48-05a3-414d-a636-0218adcb8cf0)

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/96cdaea2-f43f-47d3-8695-db2505157592)

I don't think this was available previously (it says api version 2019-12-1... don't remember seeing this before.) Remind me if I'm forgetting something and we've seen this already!
