### ISSUE TITLE
Data Ingestion Asks - Prose [Tracking]

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#703]
**For Model Builder:**
[P1 - August Release] Can we move InferColumns into data screen? Can PROSE infer column types for us? (731)

- Adding this functionality with Advanced Options work. Issue tracking #894
- See PROSE example code here https://app.zenhub.com/files/186917455/c3748d27-2c7a-4b4f-bdb4-409238e61671/download

[P0] Can we use PROSE to clean data and write a new training file for us? (416)
- [ ] Find/Clean Dirty Rows
- [ ] Provide Errors

[P1] Could we do better than write to a new file? 
- [ ] Stream Read and Fix Data
- [ ] Fix to IDV (IDataView)

[P2] Can we use PROSE to convert various files into .csv and .tsv (e.g. json file)

**For PROSE:**
- [ ] Shared telemetry dashboard to track progress

**Comment by beccamc** [comment]
This isn't a priority now. When we figure out the dataprep story this may come back.
